### ISSUE TITLE
Royalties are not being paid out on first sales

### ISSUE THREAD

**Issue by mynamebrody** [rariblecom/protocol-issues#2]
Royalties should always be paid out regardless of if it is the first sale or not. This is important if you are trying to split royalties amongst various creators or people who need to be paid out.

**Comment by evgenynacu** [comment]
This should be fixed now
Tested in auto tests. Not manually tested yet

**Comment by evgenynacu** [comment]
Not yet deployed on mainnet. will post comment soon

**Comment by evgenynacu** [comment]
Deployed!
